# Generated by Django 5.2.17 on 2026-08-12 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('customers', '0001_initial'),
        ('tenants', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='customer_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bills', to='customers.customeraccount'),
        ),
        migrations.AddField(
            model_name='bill',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='billitem',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='billing.bill'),
        ),
        migrations.AddField(
            model_name='billitem',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='revenuesource',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='bill',
            name='revenue_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bills', to='billing.revenuesource'),
        ),
        migrations.AddConstraint(
            model_name='revenuesource',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='unique_revenue_source_name_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='bill',
            constraint=models.UniqueConstraint(fields=('tenant', 'bill_number'), name='unique_bill_number_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='bill',
            constraint=models.UniqueConstraint(condition=models.Q(('external_reference__gt', '')), fields=('tenant', 'external_reference'), name='unique_bill_external_reference_per_tenant'),
        ),
    ]
