# Generated by Django 5.2.17 on 2026-08-12 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('control_numbers', '0001_initial'),
        ('customers', '0001_initial'),
        ('tenants', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlnumber',
            name='customer_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='control_numbers', to='customers.customeraccount'),
        ),
        migrations.AddField(
            model_name='controlnumber',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddConstraint(
            model_name='controlnumber',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('bill__isnull', False), ('customer_account__isnull', True)), models.Q(('bill__isnull', True), ('customer_account__isnull', False)), _connector='OR'), name='control_number_exactly_one_owner'),
        ),
        migrations.AddConstraint(
            model_name='controlnumber',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('customer_account',), name='unique_active_control_number_per_account'),
        ),
    ]
