# Generated by Django 5.2.17 on 2026-08-12 09:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('sector', models.CharField(choices=[('education', 'Education'), ('healthcare', 'Healthcare'), ('retail', 'Retail'), ('hospitality', 'Hospitality'), ('property', 'Property management'), ('professional_services', 'Professional services'), ('ngo', 'NGO'), ('religious', 'Religious organization'), ('training', 'Training institution'), ('membership', 'Membership organization'), ('utilities', 'Utilities'), ('association', 'Association'), ('government_adjacent', 'Government-adjacent / private institution'), ('other', 'Other')], default='other', max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending approval'), ('active', 'Active'), ('suspended', 'Suspended'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=32)),
                ('default_currency', models.CharField(default='TZS', max_length=3)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TenantMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('tenant_admin', 'Tenant Administrator'), ('finance_manager', 'Finance Manager'), ('accountant', 'Accountant'), ('billing_officer', 'Billing Officer'), ('reconciliation_officer', 'Reconciliation Officer'), ('viewer', 'Viewer'), ('api_client', 'API Client')], max_length=32)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['tenant__name', 'user__email'],
            },
        ),
    ]
