# Generated by Django 5.2.17 on 2026-08-12 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='fee_refund_policy',
            field=models.CharField(choices=[('clawback', 'Claw back platform fee on refund/reversal'), ('retain', 'Retain platform fee on refund/reversal')], default='clawback', max_length=16),
        ),
    ]
