# Generated by Django 5.2.17 on 2026-08-12 12:35

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0002_payment_settlement_batch'),
        ('tenants', '0003_tenant_fee_refund_policy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receipt_number', models.CharField(editable=False, max_length=40)),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('institution_name', models.CharField(max_length=200)),
                ('customer_name', models.CharField(max_length=255)),
                ('bill_number', models.CharField(blank=True, max_length=40)),
                ('control_number', models.CharField(max_length=32)),
                ('payment_reference', models.CharField(max_length=64)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency', models.CharField(default='TZS', max_length=3)),
                ('payment_channel_label', models.CharField(max_length=200)),
                ('remaining_balance_at_issue', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='receipt', to='payments.payment')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-issued_at'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'receipt_number'), name='unique_receipt_number_per_tenant')],
            },
        ),
    ]
