# Generated by Django 5.2.17 on 2026-08-12 10:41

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0002_initial'),
        ('control_numbers', '0002_initial'),
        ('providers', '0001_initial'),
        ('tenants', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('pending', 'Pending'), ('successful', 'Successful'), ('failed', 'Failed'), ('unknown', 'Unknown'), ('expired', 'Expired'), ('reversed', 'Reversed'), ('refunded', 'Refunded')], default='initiated', max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency', models.CharField(default='TZS', max_length=3)),
                ('payer_reference', models.CharField(blank=True, max_length=100)),
                ('merchant_reference', models.CharField(editable=False, max_length=64, unique=True)),
                ('provider_reference', models.CharField(blank=True, db_index=True, max_length=100)),
                ('idempotency_key', models.CharField(blank=True, max_length=100)),
                ('initiated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.CharField(blank=True, max_length=255)),
                ('raw_provider_response', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='providers.paymentchannel')),
                ('control_number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='control_numbers.controlnumber')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='providers.paymentprovider')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-initiated_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_allocations', to='billing.bill')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='payments.payment')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentCallbackEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_event_id', models.CharField(max_length=150)),
                ('outcome', models.CharField(choices=[('processed', 'Processed'), ('duplicate', 'Duplicate'), ('unmatched', 'Unmatched'), ('invalid_signature', 'Invalid signature')], max_length=20)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='callback_events', to='payments.payment')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='callback_events', to='providers.paymentprovider')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__gt', '')), fields=('tenant', 'idempotency_key'), name='unique_payment_idempotency_key_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='paymentcallbackevent',
            constraint=models.UniqueConstraint(condition=models.Q(('external_event_id__gt', '')), fields=('provider', 'external_event_id'), name='unique_provider_callback_event'),
        ),
    ]
