# Generated by Django 5.2.17 on 2026-08-12 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('settlement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='settlement_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='settlement.settlementbatch'),
        ),
    ]
