# Generated by Django 5.2.17 on 2026-08-12 10:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MockProviderTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('merchant_reference', models.CharField(max_length=64, unique=True)),
                ('provider_reference', models.CharField(max_length=64)),
                ('outcome', models.CharField(max_length=16)),
            ],
            options={
                'get_latest_by': 'created_at',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('is_sandbox', models.BooleanField(default=True, help_text='True for mock/sandbox providers. Must never be silently presented to a user as a real payment method.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PaymentChannel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=32)),
                ('name', models.CharField(max_length=150)),
                ('channel_type', models.CharField(choices=[('mobile_money', 'Mobile money'), ('bank', 'Bank'), ('card', 'Card'), ('other', 'Other')], max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='providers.paymentprovider')),
            ],
            options={
                'ordering': ['provider__name', 'name'],
                'constraints': [models.UniqueConstraint(fields=('provider', 'code'), name='unique_channel_code_per_provider')],
            },
        ),
    ]
