# Generated by Django 5.2.17 on 2026-08-12 11:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('ledger', '0001_initial'),
        ('tenants', '0003_tenant_fee_refund_policy'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevenueEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('control_number_created', 'Control number created'), ('control_number_reused', 'Control number reused'), ('payment_successful', 'Payment successful'), ('payment_failed', 'Payment failed'), ('payment_duplicate', 'Duplicate payment/webhook'), ('payment_reversed', 'Payment reversed'), ('payment_refunded', 'Payment refunded')], db_index=True, max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency', models.CharField(default='TZS', max_length=3)),
                ('object_id', models.CharField(blank=True, max_length=64)),
                ('correlation_id', models.CharField(blank=True, max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('ledger_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revenue_events', to='ledger.ledgerentry')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'event_type', 'created_at'], name='revenue_rev_tenant__ff96ab_idx')],
            },
        ),
    ]
