"""
Payment domain models. See docs/PAYMENT_LIFECYCLE.md for the full state
machine and the UNKNOWN-handling rule this must respect.
"""

import uuid

from django.core.exceptions import ValidationError
from django.db import models
from django.utils import timezone

from apps.core.models import BaseModel, TenantScopedModel
from apps.core.money import money_field_kwargs


class PaymentStatus(models.TextChoices):
    INITIATED = "initiated", "Initiated"
    PENDING = "pending", "Pending"
    SUCCESSFUL = "successful", "Successful"
    FAILED = "failed", "Failed"
    UNKNOWN = "unknown", "Unknown"
    EXPIRED = "expired", "Expired"
    REVERSED = "reversed", "Reversed"
    REFUNDED = "refunded", "Refunded"


# See docs/PAYMENT_LIFECYCLE.md. UNKNOWN is reachable from INITIATED or
# PENDING (a timeout can happen at either stage) and resolves only via an
# explicit provider query — see apps.payments.services.query_payment.
# UNKNOWN -> UNKNOWN (still inconclusive after a query) is intentionally
# not listed as a "transition" at all — the status doesn't change, so
# transition_to() is simply not called in that case.
ALLOWED_TRANSITIONS = {
    PaymentStatus.INITIATED: {PaymentStatus.PENDING, PaymentStatus.SUCCESSFUL, PaymentStatus.FAILED, PaymentStatus.UNKNOWN},
    PaymentStatus.PENDING: {PaymentStatus.SUCCESSFUL, PaymentStatus.FAILED, PaymentStatus.UNKNOWN, PaymentStatus.EXPIRED},
    PaymentStatus.UNKNOWN: {PaymentStatus.SUCCESSFUL, PaymentStatus.FAILED},
    PaymentStatus.SUCCESSFUL: {PaymentStatus.REVERSED, PaymentStatus.REFUNDED},
    PaymentStatus.FAILED: set(),
    PaymentStatus.EXPIRED: set(),
    PaymentStatus.REVERSED: set(),
    PaymentStatus.REFUNDED: set(),
}


class Payment(TenantScopedModel):
    control_number = models.ForeignKey(
        "control_numbers.ControlNumber", on_delete=models.PROTECT, related_name="payments"
    )
    provider = models.ForeignKey("providers.PaymentProvider", on_delete=models.PROTECT, related_name="payments")
    channel = models.ForeignKey(
        "providers.PaymentChannel", null=True, blank=True, on_delete=models.PROTECT, related_name="payments"
    )

    status = models.CharField(max_length=16, choices=PaymentStatus.choices, default=PaymentStatus.INITIATED)
    amount = models.DecimalField(**money_field_kwargs())
    currency = models.CharField(max_length=3, default="TZS")

    payer_reference = models.CharField(max_length=100, blank=True)

    # Generated by KUSANYA before calling the provider — always known,
    # even if the provider's response never arrives. See
    # apps.providers.base.PaymentProviderAdapter.initiate_payment and
    # docs/PAYMENT_LIFECYCLE.md.
    merchant_reference = models.CharField(max_length=64, unique=True, editable=False)
    provider_reference = models.CharField(max_length=100, blank=True, db_index=True)

    # Client-supplied idempotency key for payment *initiation* (build spec
    # section 14) — distinct from merchant_reference, which KUSANYA
    # generates internally regardless of whether the caller supplied one.
    idempotency_key = models.CharField(max_length=100, blank=True)

    initiated_at = models.DateTimeField(default=timezone.now)
    completed_at = models.DateTimeField(null=True, blank=True)
    failure_reason = models.CharField(max_length=255, blank=True)

    raw_provider_response = models.JSONField(default=dict, blank=True)
    metadata = models.JSONField(default=dict, blank=True)

    class Meta:
        ordering = ["-initiated_at"]
        constraints = [
            models.UniqueConstraint(
                fields=["tenant", "idempotency_key"],
                condition=models.Q(idempotency_key__gt=""),
                name="unique_payment_idempotency_key_per_tenant",
            )
        ]

    def __str__(self):
        return f"{self.merchant_reference} — {self.amount} {self.currency} ({self.status})"

    def save(self, *args, **kwargs):
        if not self.merchant_reference:
            self.merchant_reference = f"PAY-{uuid.uuid4().hex[:16].upper()}"
        super().save(*args, **kwargs)

    def transition_to(self, new_status: str, *, failure_reason: str = "") -> None:
        allowed = ALLOWED_TRANSITIONS.get(self.status, set())
        if new_status not in allowed:
            raise ValidationError(
                f"Cannot transition payment from '{self.status}' to '{new_status}'."
            )
        self.status = new_status
        if new_status in (PaymentStatus.SUCCESSFUL, PaymentStatus.FAILED, PaymentStatus.REVERSED, PaymentStatus.REFUNDED):
            self.completed_at = timezone.now()
        if failure_reason:
            self.failure_reason = failure_reason
        self.save(update_fields=["status", "completed_at", "failure_reason", "updated_at"])


class PaymentAllocation(TenantScopedModel):
    """How a successful payment's amount is applied to a specific bill.

    For a one-time (bill-bound) control number this is always exactly one
    row covering the full payment amount — auto-created by the
    orchestrator on SUCCESSFUL. For a persistent (account-bound) control
    number spanning multiple bills, allocation across several unpaid
    bills (e.g. oldest-first) is Phase 4 ledger logic — not built yet, so
    no PaymentAllocation is created automatically for account-level
    payments in Phase 3 (see docs/PAYMENT_LIFECYCLE.md).
    """

    payment = models.ForeignKey(Payment, on_delete=models.PROTECT, related_name="allocations")
    bill = models.ForeignKey("billing.Bill", on_delete=models.PROTECT, related_name="payment_allocations")
    amount = models.DecimalField(**money_field_kwargs())

    class Meta:
        ordering = ["-created_at"]

    def __str__(self):
        return f"{self.amount} of {self.payment.merchant_reference} -> {self.bill.bill_number}"


class PaymentCallbackEvent(BaseModel):
    """Inbound provider-callback idempotency ledger.

    The build spec's requirement is explicit: "the same provider event
    received three times must create only one financial event." This
    table is what makes that a database-enforced guarantee rather than a
    hope: a second delivery of the same (provider, external_event_id)
    hits the UniqueConstraint below and is rejected *before* any status
    transition or webhook dispatch happens — see
    apps.payments.services.process_callback.
    """

    class Outcome(models.TextChoices):
        PROCESSED = "processed", "Processed"
        DUPLICATE = "duplicate", "Duplicate"
        UNMATCHED = "unmatched", "Unmatched"
        INVALID_SIGNATURE = "invalid_signature", "Invalid signature"

    provider = models.ForeignKey("providers.PaymentProvider", on_delete=models.PROTECT, related_name="callback_events")
    external_event_id = models.CharField(max_length=150)
    payment = models.ForeignKey(
        Payment, null=True, blank=True, on_delete=models.SET_NULL, related_name="callback_events"
    )
    outcome = models.CharField(max_length=20, choices=Outcome.choices)
    raw_payload = models.JSONField(default=dict, blank=True)

    class Meta:
        ordering = ["-created_at"]
        constraints = [
            models.UniqueConstraint(
                fields=["provider", "external_event_id"],
                condition=models.Q(external_event_id__gt=""),
                name="unique_provider_callback_event",
            )
        ]

    def __str__(self):
        return f"{self.provider.code}:{self.external_event_id} ({self.outcome})"
