# Generated by Django 5.2.17 on 2026-08-12 11:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('tenants', '0003_tenant_fee_refund_policy'),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry_type', models.CharField(choices=[('bill_amount', 'Bill amount'), ('payment_received', 'Payment received'), ('institution_entitlement', 'Institution entitlement'), ('platform_control_number_fee', 'Platform control-number fee'), ('platform_payment_fee', 'Platform payment fee'), ('provider_fee', 'Provider fee'), ('refund', 'Refund'), ('reversal', 'Reversal'), ('settlement', 'Settlement'), ('adjustment', 'Adjustment')], db_index=True, max_length=32)),
                ('account', models.CharField(choices=[('customer', 'Customer'), ('institution', 'Institution (tenant)'), ('platform', 'KUSANYA platform'), ('provider', 'Payment provider'), ('suspense', 'Suspense (unresolved/exception)')], max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency', models.CharField(default='TZS', max_length=3)),
                ('reference', models.CharField(blank=True, db_index=True, max_length=100)),
                ('correlation_id', models.CharField(blank=True, max_length=64)),
                ('object_id', models.CharField(blank=True, max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('related_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compensating_entries', to='ledger.ledgerentry')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['tenant', 'entry_type', 'created_at'], name='ledger_ledg_tenant__2d8a3f_idx'), models.Index(fields=['tenant', 'account', 'created_at'], name='ledger_ledg_tenant__455cdc_idx')],
            },
        ),
    ]
