# Generated by Django 5.2.17 on 2026-08-12 09:14

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('actor_label', models.CharField(blank=True, help_text='Human-readable actor snapshot, kept even if the user is later deleted.', max_length=255)),
                ('action', models.CharField(db_index=True, help_text='e.g. "tenant.approved"', max_length=100)),
                ('object_id', models.CharField(blank=True, max_length=64)),
                ('before', models.JSONField(blank=True, null=True)),
                ('after', models.JSONField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('correlation_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('previous_hash', models.CharField(editable=False, max_length=64)),
                ('record_hash', models.CharField(db_index=True, editable=False, max_length=64, unique=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
