"""
The provider abstraction. The payment orchestrator (apps.payments.services)
talks only to this interface — never to a specific telecom/bank API
directly. See docs/PAYMENT_PROVIDER_ARCHITECTURE.md and build spec
section 12.

Every real provider gets its own module implementing `PaymentProviderAdapter`
(none exist yet — see apps/providers/mock.py's module docstring for why).
"""

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from decimal import Decimal
from enum import Enum


class ProviderOutcome(str, Enum):
    """Normalized outcome vocabulary every adapter must map its own
    provider's status codes onto. The orchestrator only ever sees these
    four values, never a provider-specific status string."""

    PENDING = "pending"
    SUCCESSFUL = "successful"
    FAILED = "failed"
    UNKNOWN = "unknown"  # timeout / inconclusive — see docs/PAYMENT_LIFECYCLE.md


@dataclass
class ProviderResult:
    outcome: ProviderOutcome
    provider_reference: str = ""
    message: str = ""
    raw_response: dict = field(default_factory=dict)


@dataclass
class ProviderCallbackResult:
    """What an adapter extracts from a raw inbound callback payload,
    before the orchestrator matches it to a Payment."""

    external_event_id: str
    provider_reference: str
    outcome: ProviderOutcome
    raw_response: dict = field(default_factory=dict)


class ProviderError(Exception):
    """Base class for provider-adapter errors."""


class ProviderTimeoutError(ProviderError):
    """The provider request timed out — the orchestrator MUST treat this
    as UNKNOWN, never as FAILED, and must never blindly retry. See
    docs/PAYMENT_LIFECYCLE.md."""


class InvalidCallbackSignatureError(ProviderError):
    """Raised by process_callback() when the inbound signature doesn't
    verify — the orchestrator must reject the callback outright."""


class PaymentProviderAdapter(ABC):
    """One instance per (PaymentProvider row, tenant credential) in a real
    adapter; the mock adapter needs no credentials at all."""

    @abstractmethod
    def initiate_payment(
        self,
        *,
        amount: Decimal,
        currency: str,
        control_number: str,
        payer_reference: str,
        merchant_reference: str,
        metadata: dict,
    ) -> ProviderResult:
        """Ask the provider to start collecting a payment.

        `merchant_reference` is generated by KUSANYA *before* this call
        (see apps.payments.services) and is always known to us regardless
        of whether the provider's response ever arrives — real provider
        APIs accept exactly this kind of caller-supplied reference so a
        client can later query "what happened to the request I sent
        earlier," which is the only safe way to resolve a timeout. Never
        rely on the provider's own reference for that — it may not exist
        yet if the response was lost.
        """

    @abstractmethod
    def query_payment(self, *, merchant_reference: str) -> ProviderResult:
        """Ask the provider for a payment's current true status, keyed by
        OUR OWN merchant_reference (not the provider's reference — see
        initiate_payment). This is the only safe way to resolve an
        UNKNOWN payment — never a blind retry of initiate_payment()."""

    @abstractmethod
    def validate_reference(self, *, control_number: str) -> bool:
        """Whether the provider considers this control number well-formed
        for their channel (e.g. checksum validation), before attempting
        to collect against it."""

    @abstractmethod
    def process_callback(self, *, raw_payload: bytes, headers: dict) -> ProviderCallbackResult:
        """Parse + verify an inbound provider callback. Must raise
        InvalidCallbackSignatureError if the signature doesn't verify —
        never process an unverified callback."""

    @abstractmethod
    def refund(self, *, provider_reference: str, amount: Decimal) -> ProviderResult:
        ...

    @abstractmethod
    def reverse(self, *, provider_reference: str) -> ProviderResult:
        ...

    @abstractmethod
    def reconcile(self, *, provider_reference: str) -> ProviderResult:
        """Distinct from query_payment in real adapters (reconciliation
        APIs are often bulk/batch, not per-transaction) — for the mock
        adapter this just delegates to query_payment()."""

    @abstractmethod
    def health_check(self) -> bool:
        ...
