# Generated by Django 5.2.17 on 2026-08-12 11:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('providers', '0002_seed_mock_provider'),
        ('tenants', '0003_tenant_fee_refund_policy'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettlementBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(editable=False, max_length=40)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('gross_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('platform_fee_total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('provider_fee_total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('currency', models.CharField(default='TZS', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('exception', 'Exception')], default='pending', max_length=16)),
                ('settlement_date', models.DateTimeField(blank=True, null=True)),
                ('external_settlement_reference', models.CharField(blank=True, help_text="The provider/bank's own reference for the actual funds transfer — entered when marking this batch completed.", max_length=150)),
                ('notes', models.TextField(blank=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlement_batches', to='providers.paymentprovider')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-period_end'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'reference'), name='unique_settlement_batch_reference_per_tenant')],
            },
        ),
    ]
