# Generated by Django 5.2.17 on 2026-08-12 12:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0003_tenant_fee_refund_policy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('bill_created', 'Bill created'), ('control_number_generated', 'Control number generated'), ('payment_pending', 'Payment pending'), ('payment_successful', 'Payment successful'), ('payment_failed', 'Payment failed'), ('payment_partial', 'Partial payment'), ('bill_fully_paid', 'Bill fully paid'), ('balance_reminder', 'Balance reminder'), ('payment_reversed', 'Payment reversed'), ('payment_refunded', 'Payment refunded')], db_index=True, max_length=32)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('push', 'Push')], max_length=16)),
                ('recipient', models.CharField(help_text='Email address or phone number.', max_length=255)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.CharField(blank=True, max_length=500)),
                ('correlation_id', models.CharField(blank=True, max_length=64)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'status', 'created_at'], name='notificatio_tenant__d8e132_idx')],
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('bill_created', 'Bill created'), ('control_number_generated', 'Control number generated'), ('payment_pending', 'Payment pending'), ('payment_successful', 'Payment successful'), ('payment_failed', 'Payment failed'), ('payment_partial', 'Partial payment'), ('bill_fully_paid', 'Bill fully paid'), ('balance_reminder', 'Balance reminder'), ('payment_reversed', 'Payment reversed'), ('payment_refunded', 'Payment refunded')], max_length=32)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('push', 'Push')], max_length=16)),
                ('subject', models.CharField(blank=True, help_text='Ignored for SMS.', max_length=255)),
                ('body', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'ordering': ['tenant__name', 'event_type', 'channel'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'event_type', 'channel'), name='unique_template_per_tenant_event_channel')],
            },
        ),
    ]
